version: '3.8'

services:
  spring-boot-app:
    image: openjdk:8-jdk-alpine
    container_name: example
    working_dir: /app
    volumes:
      - ./target/example-1.0-SNAPSHOT.jar:/app/spring-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=example
    depends_on:
      - db
    command: ["java", "-jar", "example-1.0-SNAPSHOT.jar"]

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: